source "https://rubygems.org"

ruby '3.0.2'

gem 'sinatra', '~> 2.2.0'
gem 'activerecord', '~> 6.1.0'
gem 'sinatra-activerecord', '~> 2.0'
gem 'rake'
gem 'require_all'
gem 'sqlite3', '~> 1.4'
gem 'thin'
gem 'pry'
gem 'bcrypt'
gem 'tux'
gem 'webrick'
gem 'rack-flash3'
gem 'logger'

group :development do
  gem 'shotgun'
end

group :test do
  gem 'rspec'
  gem 'capybara'
  gem 'rack-test'
  gem 'database_cleaner'
end