development:
  adapter: postgresql
  database: vintran_development
  host: localhost
  pool: 5
  username: vintran
  password: nollie

production:
  adapter: postgresql
  database: vintran_production
  host: <%= ENV["DATABASE_HOST"] %>
  pool: 5
  username: vintran
  password: nollie